############################################################
# Dockerfile to build woku container images
# Based on Nginx
############################################################

# Set the base image
FROM nginx:latest

# File Author
MAINTAINER ascoders www.ziyihuang@gmail.com

COPY nginx.conf /etc/nginx/nginx.conf

# Expose the default port
EXPOSE 80