language: node_js
os:
- linux
install:
- npm install yarn -g
- yarn
node_js:
- 6.9.2
- 7.3.0
before_script:
- npm run tsc
script:
- npm run production
- npm test
before_install:
- openssl aes-256-cbc -K $encrypted_ff3bfcc4663d_key -iv $encrypted_ff3bfcc4663d_iv
  -in .travis/rsa.enc -out ~/.ssh/id_rsa -d
after_success:
# Set the permission of the key
- chmod 600 ~/.ssh/id_rsa
# Start SSH agent
- eval "$(ssh-agent -s)"
# Add the private key to the system
- ssh-add ~/.ssh/id_rsa
# Copy SSH config
- cp .travis/ssh_config ~/.ssh/config
# Run bash
- bash deploy.sh