db:
  build: ./dockers/mysql
  restart: always
  ports:
    - "3306:3306"
  volumes:
    - /tmp/wokudata:/var/lib/mysql
  environment:
    MYSQL_ROOT_PASSWORD: test

redis:
  image: redis
  restart: always
  ports:
    - "6379:6379"
  volumes:
    - /tmp/wokuredis:/data
  command: redis-server --appendonly yes