app:
  build: ./
  restart: always
  ports:
    - "5000:8000"
  links:
    - db

db:
  build: ./dockers/mysql
  restart: always
  ports:
    - "3306:3306"
  volumes:
    - /tmp/wokudata:/var/lib/mysql
  environment:
    MYSQL_ROOT_PASSWORD: test