############################################################
# Dockerfile to build woku container images
# Based on node
############################################################

# Set the base image
FROM node:latest

# File Author
MAINTAINER ascoders www.ziyihuang@gmail.com

# Change work dir
WORKDIR /work

# Expose the default port
EXPOSE 8080 9091

# Run Container
CMD npm run start-before && npm start